paths:
  /api/ambient-api-server/v1/project_settings:
    get:
      summary: Returns a list of project settings
      security:
        - Bearer: []
      responses:
        '200':
          description: A JSON array of project settings objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSettingsList'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '403':
          description: Unauthorized to perform operation
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/orderBy'
        - $ref: '#/components/parameters/fields'
    post:
      summary: Create a new project settings
      security:
        - Bearer: []
      requestBody:
        description: Project settings data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectSettings'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSettings'
        '400':
          description: Validation errors occurred
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '403':
          description: Unauthorized to perform operation
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '409':
          description: Project settings already exists
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          description: An unexpected error occurred creating the project settings
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
  /api/ambient-api-server/v1/project_settings/{id}:
    get:
      summary: Get a project settings by id
      security:
        - Bearer: []
      responses:
        '200':
          description: Project settings found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSettings'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '403':
          description: Unauthorized to perform operation
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '404':
          description: No project settings with specified id exists
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
    patch:
      summary: Update a project settings
      security:
        - Bearer: []
      requestBody:
        description: Updated project settings data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectSettingsPatchRequest'
      responses:
        '200':
          description: Project settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectSettings'
        '400':
          description: Validation errors occurred
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '403':
          description: Unauthorized to perform operation
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '404':
          description: No project settings with specified id exists
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '409':
          description: Project settings already exists
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          description: Unexpected error updating project settings
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
    delete:
      summary: Delete a project settings by id
      security:
        - Bearer: []
      responses:
        '204':
          description: Project settings deleted successfully
        '401':
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '403':
          description: Unauthorized to perform operation
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '404':
          description: No project settings with specified id exists
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
        '500':
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'openapi.yaml#/components/schemas/Error'
    parameters:
      - $ref: '#/components/parameters/id'
components:
  schemas:
    ProjectSettings:
      allOf:
        - $ref: 'openapi.yaml#/components/schemas/ObjectReference'
        - type: object
          required:
            - project_id
          properties:
            project_id:
              type: string
            group_access:
              type: string
            runner_secrets:
              type: string
            repositories:
              type: string
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
    ProjectSettingsList:
      allOf:
        - $ref: 'openapi.yaml#/components/schemas/List'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/ProjectSettings'
    ProjectSettingsPatchRequest:
      type: object
      properties:
        project_id:
          type: string
        group_access:
          type: string
        runner_secrets:
          type: string
        repositories:
          type: string
  parameters:
      id:
        name: id
        in: path
        description: The id of record
        required: true
        schema:
          type: string
      page:
        name: page
        in: query
        description: Page number of record list when record list exceeds specified page size
        schema:
          type: integer
          default: 1
          minimum: 1
        required: false
      size:
        name: size
        in: query
        description: Maximum number of records to return
        schema:
          type: integer
          default: 100
          minimum: 0
        required: false
      search:
        name: search
        in: query
        required: false
        description: Specifies the search criteria
        schema:
          type: string
      orderBy:
        name: orderBy
        in: query
        required: false
        description: Specifies the order by criteria
        schema:
          type: string
      fields:
        name: fields
        in: query
        required: false
        description: Supplies a comma-separated list of fields to be returned
        schema:
          type: string
