---
apiVersion: v1
kind: Secret
metadata:
  name: ambient-api-server-db
  labels:
    app: ambient-api-server
    component: database
type: Opaque
stringData:
  db.host: ambient-api-server-db
  db.port: "5432"
  db.name: ambient_api_server
  db.user: ambient
  db.password: TheBlurstOfTimes

---
apiVersion: v1
kind: Secret
metadata:
  name: ambient-api-server
  labels:
    app: ambient-api-server
    component: api
type: Opaque
stringData:
  sentry.key: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ambient-api-server-auth
  labels:
    app: ambient-api-server
    component: auth
data:
  jwks.json: |
    {
      "keys": []
    }
  acl.yml: |
    - claim: email
      pattern: ^.*@(redhat\.com|ambient\.code)$