# Unleash UI Route for production (OpenShift)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: unleash-route
  labels:
    app: unleash
    app.kubernetes.io/name: unleash
spec:
  to:
    kind: Service
    name: unleash
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
